#!/bin/sh

if [ -x "$(which pacman)" ]; then
    if [ ! -x "$(which yay)" ]; then
        echo "Installing yay"
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
        cd ..
        rm -rf yay
    fi

    PKGLIST="yay yadm"

    ## Tools
    PKGLIST+=" htop"
    
    ## GNOME
    #PKGLIST+=" gnome-shell"

    ## Apps
    PKGLIST+=" keybase keybase-gui kbfs brave-bin spotify discord betterdiscordctl-git"

    ## Games
    #PKGLIST+=" steam lutris"

    ## Java
    PKGLIST+=" jdk-openjdk jdk8-openjdk"

    ## Dev tools
    PKGLIST+=" git git-crypt code nodejs nvm"

    # ## NVIDIA Drivers
    # if [ $(lspci  -v -s  $(lspci | grep ' VGA ' | cut -d" " -f 1) | grep NVIDIA | wc -l) -gt 0]; then
    #     PKGLIST+=" nvidia nvidia-utils"
    #     NVIDIA=1
    # fi

    echo "Updating mirrorlist"
    yay -S --needed reflector
    $HOME/scripts/update-mirrors.sh

    echo "Installing packages"
    yay -Syu --needed $PKGLIST

    # if [ $NVIDIA = 1]; then
    #     sudo nvidia-xconfig
    # fi
fi

## Symlinks
#ln -s ~/.renpy ~/Dokumenty/Games/RenPy
#ln -s ~/.paradoxinteractive ~/Dokumenty/Games/Paradox\ Interactive

## Keybase
if [ -x "$(which keybase)" ]; then
    systemctl enable --user --now keybase
    keybase login m00nlit

    keybase ctl autostart --disable

    keybase config set mountdir $HOME/keybase
    systemctl enable --user --now kbfs

    keybase pgp export | gpg --import
    keybase pgp export -s | gpg --allow-secret-key-import --import

    yadm git-crypt unlock
fi

## BetterDiscord
if [ -x "$(which betterdiscordctl)" ]; then
    # if [ ! -x "$(which betterdiscordctl)" ]; then
    #     curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl
    #     chmod +x betterdiscordctl
    #     sudo mv betterdiscordctl /usr/local/bin
    # fi

    betterdiscordctl install
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:lmarianski/dotfiles.git"
