#!/bin/bash

(

#source ~/.bashrc
#export -p

#read -t 5 -p "I am going to wait for 5 seconds only ..."


[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME=$HOME/.config
[ -z "$XDG_CACHE_HOME" ] && XDG_CACHE_HOME=$HOME/.cache
[ -z "$XDG_DATA_HOME" ] && XDG_DATA_HOME=$HOME/.local/share



HOME=$XDG_DATA_HOME/Steam

relink() {
  echo $1 $2

  if [ -d "$2" ]; then
    rm -rf "$2"
  else
    unlink "$2"
  fi

  ln -s "$1" "$2"
}

relink "$XDG_CONFIG_HOME" "$HOME/.config"
relink "$XDG_CACHE_HOME" "$HOME/.cache"
relink "$XDG_DATA_HOME/.." "$HOME/.local"
exec /usr/bin/steam "$@"
#read -t 5 -p "I am going to wait for 5 seconds only ..."
) > /home/m00n/steam-log.txt
