#!/usr/bin/env sh

#source ~/.bashrc
#export -p

HOME=$XDG_DATA_HOME/Steam

relink() {
  echo $1 $2

  if [ -d "$2" ]; then
    rm -rf "$2"
  else
    unlink "$2"
  fi

  ln -s "$1" "$2"
}

relink "$XDG_CONFIG_HOME" "$HOME/.config"
relink "$XDG_CACHE_HOME" "$HOME/.cache"
relink "$XDG_DATA_HOME" "$HOME/.local"

exec gamemoderun /usr/bin/steam "$@"
